attack:
  epsilon: 0.0313725
  step_size: 0.0235294
  steps: 10
batch_size: 32
dataset:
  max_samples: 100
  name: nlphuji/flickr30k
  split: test
defenses:
# Alpha sweep (0.1 to 0.9, step 0.1) for final_norm
- alpha: 0.1
  method: cp
  name: CP Final Norm (R=64, alpha=0.1)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.2
  method: cp
  name: CP Final Norm (R=64, alpha=0.2)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.3
  method: cp
  name: CP Final Norm (R=64, alpha=0.3)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.4
  method: cp
  name: CP Final Norm (R=64, alpha=0.4)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=64, alpha=0.5)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.6
  method: cp
  name: CP Final Norm (R=64, alpha=0.6)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.7
  method: cp
  name: CP Final Norm (R=64, alpha=0.7)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.8
  method: cp
  name: CP Final Norm (R=64, alpha=0.8)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.9
  method: cp
  name: CP Final Norm (R=64, alpha=0.9)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1

# Rank sweep (16 to 256, doubling) for final_norm
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=16, alpha=0.5)
  rank: 16
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=32, alpha=0.5)
  rank: 32
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=64, alpha=0.5)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=128, alpha=0.5)
  rank: 128
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=256, alpha=0.5)
  rank: 256
  target_layer: final_norm
  vision_layer_idx: -1

# Layer analysis (testing all layers with same params)
- alpha: 0.5
  method: cp
  name: CP Final Norm (R=64, alpha=0.5)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Attention (R=64, alpha=0.5)
  rank: 64
  target_layer: attention
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP MLP (R=64, alpha=0.5)
  rank: 64
  target_layer: mlp
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP QKV (R=64, alpha=0.5)
  rank: 64
  target_layer: qkv
  vision_layer_idx: -1
- alpha: 0.5
  method: cp
  name: CP Projection (R=64, alpha=0.5)
  rank: 64
  target_layer: projection
  vision_layer_idx: -1

# Method comparison (CP vs Tucker)
- alpha: 0.5
  method: tucker
  name: Tucker Final Norm (R=64, alpha=0.5)
  rank: 64
  target_layer: final_norm
  vision_layer_idx: -1

# Multi-layer experiments
# Two layers (existing)
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: attention
    vision_layer_idx: -1
  name: CP Multi-Layer (Final Norm + Attention)
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: mlp
    vision_layer_idx: -1
  name: CP Multi-Layer (Final Norm + MLP)

# Last 2 layers
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -2
  name: CP Multi-Layer (Last 2 Layers)

# Last 3 layers
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -2
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -3
  name: CP Multi-Layer (Last 3 Layers)

# Last 4 layers
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -2
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -3
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -4
  name: CP Multi-Layer (Last 4 Layers)

# Last 5 layers
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -2
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -3
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -4
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -5
  name: CP Multi-Layer (Last 5 Layers)

# All final_norm layers (12 layers for CLIP ViT-base)
- layers:
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -1
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -2
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -3
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -4
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -5
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -6
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -7
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -8
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -9
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -10
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -11
  - alpha: 0.5
    method: cp
    rank: 64
    target_layer: final_norm
    vision_layer_idx: -12
  name: CP Multi-Layer (All Final Norm Layers)

model:
  name: clip
  variant: vit-base-patch32
num_workers: 4
results_dir: results/
seed: 42 