# Alpha parameter sensitivity analysis (COCO)
seed: 42
results_dir: "results"
batch_size: 32
num_workers: 4

model:
  name: "clip"
  variant: "vit-base-patch32"

dataset:
  name: "shunk031/MSCOCO"
  year: 2014
  coco_task: "captions"
  split: "train"
  max_samples: 1000
  trust_remote_code: true

attack:
  epsilon: 0.0313725 # 8/255
  steps: 10
  step_size: 0.0235294 # 6/255

defenses:
  - name: "CP Final Norm (alpha=0.1)"
    method: "cp"
    rank: 64
    alpha: 0.1
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.2)"
    method: "cp"
    rank: 64
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.3)"
    method: "cp"
    rank: 64
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.4)"
    method: "cp"
    rank: 64
    alpha: 0.4
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.5)"
    method: "cp"
    rank: 64
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.6)"
    method: "cp"
    rank: 64
    alpha: 0.6
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.7)"
    method: "cp"
    rank: 64
    alpha: 0.7
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.8)"
    method: "cp"
    rank: 64
    alpha: 0.8
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (alpha=0.9)"
    method: "cp"
    rank: 64
    alpha: 0.9
    target_layer: "final_norm"
    vision_layer_idx: -1