# Configuration for tensor decomposition defense experiments

# Random seed for reproducibility
random_seed: 42

# Results directory (will be appended with timestamp)
results_dir: "results"

# Maximum number of batches to process (set to null to process all)
max_batches: 5

# Model configuration
model:
  type: "clip" # "clip" or "llava"
  name: "openai/clip-vit-base-patch32" # Model identifier

# Dataset configuration
dataset:
  name: "nlphuji/flickr30k" # Dataset identifier
  split: "test" # Dataset split
  max_samples: 1000 # Maximum number of samples to use
  batch_size: 32 # Batch size for dataloader
  num_workers: 4 # Number of worker processes for dataloader

# Attack configuration
attack:
  type: "pgd" # "pgd" or "fgsm"
  epsilon: 0.0313 # 8/255
  steps: 2 # Number of attack steps (for PGD)
  step_size: 0.0235 # 6/255 (for PGD)
  random_start: true # Whether to use random initialization (for PGD)

# Defense configurations
defenses:
  # CP Decomposition on final normalization layer
  - name: "CP Final Norm (R=64, alpha=0.5)"
    type: "targeted"
    method: "cp"
    rank: 64
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1

  # Compare different alpha values
  - name: "CP Final Norm (R=64, alpha=0.3)"
    type: "targeted"
    method: "cp"
    rank: 64
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "CP Final Norm (R=64, alpha=0.7)"
    type: "targeted"
    method: "cp"
    rank: 64
    alpha: 0.7
    target_layer: "final_norm"
    vision_layer_idx: -1

  # Compare different ranks
  - name: "CP Final Norm (R=32, alpha=0.5)"
    type: "targeted"
    method: "cp"
    rank: 32
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "CP Final Norm (R=128, alpha=0.5)"
    type: "targeted"
    method: "cp"
    rank: 128
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1

  # Compare different decomposition methods
  - name: "Tucker Final Norm (R=64, alpha=0.5)"
    type: "targeted"
    method: "tucker"
    rank: 64
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "TT Final Norm (R=64, alpha=0.5)"
    type: "targeted"
    method: "tt"
    rank: 64
    alpha: 0.5
    target_layer: "final_norm"
    vision_layer_idx: -1

  # Compare different layer types
  - name: "CP Attention (R=64, alpha=0.5)"
    type: "targeted"
    method: "cp"
    rank: 64
    alpha: 0.5
    target_layer: "attention"
    vision_layer_idx: -1

  - name: "CP MLP (R=64, alpha=0.5)"
    type: "targeted"
    method: "cp"
    rank: 64
    alpha: 0.5
    target_layer: "mlp"
    vision_layer_idx: -1

  # Multi-layer defense example
  - name: "Multi-Layer Defense (2 Layers)"
    type: "multilayer"
    layer_configs:
      - method: "cp"
        rank: 64
        alpha: 0.5
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.5
        target_layer: "final_norm"
        vision_layer_idx: -2
