# Flickr30k experiment testing rank sensitivity for Tensor Train decomposition
seed: 42
results_dir: "results"
batch_size: 32
num_workers: 4

model:
  name: "clip"
  variant: "vit-base-patch32"

dataset:
  name: "nlphuji/flickr30k"
  split: "test"
  max_samples: 1000
  trust_remote_code: true

attack:
  epsilon: 0.0313725 # 8/255
  steps: 10
  step_size: 0.0235294 # 6/255

defenses:
  # Tensor Train Decomposition with different rank values
  - name: "TT Rank 8"
    method: "tt"
    rank: 8
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "TT Rank 16"
    method: "tt"
    rank: 16
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "TT Rank 32"
    method: "tt"
    rank: 32
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1


  - name: "TT Rank 48"
    method: "tt"
    rank: 48
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1



  - name: "TT Rank 64"
    method: "tt"
    rank: 64
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1


  - name: "TT Rank 80"
    method: "tt"
    rank: 80
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1


  - name: "TT Rank 96"
    method: "tt"
    rank: 96
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "TT Rank 256" 
    method: "tt"
    rank: 256
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1

  - name: "TT Rank 512" 
    method: "tt"
    rank: 512
    alpha: 0.2
    target_layer: "final_norm"
    vision_layer_idx: -1

