# Multi-layer defense analysis (Flickr30k)
seed: 42
results_dir: "results"
batch_size: 32
num_workers: 4

model:
  name: "clip"
  variant: "vit-base-patch32"

dataset:
  name: "nlphuji/flickr30k"
  split: "test"
  max_samples: 1000
  trust_remote_code: true

attack:
  epsilon: 0.0313725 # 8/255
  steps: 10
  step_size: 0.0235294 # 6/255

defenses:
  - name: "CP Final Norm (Single Layer)"
    method: "cp"
    rank: 64
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Multi-Layer (2 Layers)"
    layers:
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -2
        
  - name: "CP Multi-Layer (3 Layers)"
    layers:
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -2
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -3
        
  - name: "CP Multi-Layer (4 Layers)"
    layers:
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -2
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -3
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -4
        
  - name: "CP Multi-Layer (5 Layers)"
    layers:
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -2
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -3
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -4
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -5
        
  - name: "CP Multi-Layer (All Layers)"
    layers:
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -1
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -2
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -3
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -4
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -5
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -6
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -7
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -8
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -9
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -10
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -11
      - method: "cp"
        rank: 64
        alpha: 0.3
        target_layer: "final_norm"
        vision_layer_idx: -12