# Rank parameter sensitivity analysis (Flickr30k)
seed: 42
results_dir: "results"
batch_size: 32
num_workers: 4

model:
  name: "clip"
  variant: "vit-base-patch32"

dataset:
  name: "nlphuji/flickr30k"
  split: "test"
  max_samples: 1000
  trust_remote_code: true

attack:
  epsilon: 0.0313725 # 8/255
  steps: 10
  step_size: 0.0235294 # 6/255

defenses:
  - name: "CP Final Norm (R=16)"
    method: "cp"
    rank: 16
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (R=32)"
    method: "cp"
    rank: 32
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (R=64)"
    method: "cp"
    rank: 64
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (R=128)"
    method: "cp"
    rank: 128
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1
    
  - name: "CP Final Norm (R=256)"
    method: "cp"
    rank: 256
    alpha: 0.3
    target_layer: "final_norm"
    vision_layer_idx: -1